export enum Parcours {
  ELEMENTARY = "1 ELEMENTARY",
  PRE_INTERMEDIATE = "2 PRE INTERMEDIATE",
  INTERMEDIATE = "3 INTERMEDIATE",
  UPPER_INTERMEDIATE = "4 UPPER INTERMEDIATE",
  ADVANCED = "5 ADVANCED",
  BAC = "6 BAC",
}
